 ERROR root [0x00000688] [2020-10-28 00:00:36,612] - Components::removeComponentByChannel: logger : 210002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  INFO root [0x00000688] [2020-10-28 00:00:36,620] - The following logs sent to logger failed:
  WARN root [0x00000688] [2020-10-28 00:00:36,621] - ==> [2020-10-28 00:00:36 610] TCPPacketReceiver::processPendingEvents(192.168.2.246:49801): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000688] [2020-10-28 00:00:36,622] - ==> [2020-10-28 00:00:36 619] Components::removeComponentByChannel: logger : 210002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  WARN root [0x00000688] [2020-10-28 00:00:36,694] - TCPPacketReceiver::processPendingEvents(192.168.2.246:49802): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000688] [2020-10-28 00:00:36,697] - Components::removeComponentByChannel: dbmgr : 42002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  INFO root [0x00000688] [2020-10-28 00:00:36,703] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00000688] [2020-10-28 00:00:36,704] - onBaseAppShutDown: state=0
  INFO root [0x00000688] [2020-10-28 00:00:36,705] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00000688] [2020-10-28 00:00:36,705] - onBaseAppShutDown: state=1
  INFO root [0x00000688] [2020-10-28 00:00:36,705] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00000688] [2020-10-28 00:00:36,706] - onBaseAppShutDown: state=2
 DEBUG root [0x00000688] [2020-10-28 00:00:36,723] - Halls::~Halls(): 10001
 DEBUG root [0x00000688] [2020-10-28 00:00:36,728] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000688] [2020-10-28 00:00:36,729] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00000688] [2020-10-28 00:00:36,729] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00000688] [2020-10-28 00:00:36,729] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000688] [2020-10-28 00:00:36,729] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00000688] [2020-10-28 00:00:36,730] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000688] [2020-10-28 00:00:36,730] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000688] [2020-10-28 00:00:36,731] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00000688] [2020-10-28 00:00:36,751] - Script::uninstall(): is successfully!
 DEBUG root [0x00000688] [2020-10-28 00:00:36,751] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002b08] [2020-10-28 20:11:34,498] - 
  INFO root [0x00002b08] [2020-10-28 20:11:34,499] - -----------------------------------------------------------------------------------------


  INFO root [0x00002b08] [2020-10-28 20:11:34,500] - Resmgr::initialize: KBE_ROOT=D:/kbengine_24pic/
  INFO root [0x00002b08] [2020-10-28 20:11:34,501] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine_24pic/kbe/res/;D:/kbengine_24pic/kbengine_stone_assets/;D:/kbengine_24pic/kbengine_stone_assets/scripts/;D:/kbengine_24pic/kbengine_stone_assets/res/
  INFO root [0x00002b08] [2020-10-28 20:11:34,501] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine_24pic/kbe/bin/server/
  INFO root [0x00002b08] [2020-10-28 20:11:34,506] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.2.246 ( 192.168.2.246:20015 )
  INFO root [0x00002b08] [2020-10-28 20:11:34,506] - NetworkInterface::initialize(EXTERNAL): address 192.168.2.246:20015, SOMAXCONN=128.
  INFO root [0x00002b08] [2020-10-28 20:11:34,508] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.2.246 ( 192.168.2.246:50331 )
  INFO root [0x00002b08] [2020-10-28 20:11:34,509] - NetworkInterface::initialize(INTERNAL): address 192.168.2.246:50331, SOMAXCONN=128.
  INFO root [0x00002b08] [2020-10-28 20:11:34,509] - server-configs:
  INFO root [0x00002b08] [2020-10-28 20:11:34,509] - 	gameUpdateHertz : 30
  INFO root [0x00002b08] [2020-10-28 20:11:34,509] - 	entryScriptFile : kbemain
  INFO root [0x00002b08] [2020-10-28 20:11:34,509] - 	internalAddr : 192.168.2.246:50331
  INFO root [0x00002b08] [2020-10-28 20:11:34,509] - 	externalAddr : 192.168.2.246:20015
  INFO root [0x00002b08] [2020-10-28 20:11:34,509] - 	componentID : 720012
  INFO root [0x00002b08] [2020-10-28 20:11:34,627] - Components::findLogger: found logger, addr:192.168.2.246:50313
  INFO root [0x00002b08] [2020-10-28 20:11:34,627] - Components::addComponent: reset orderLog, uid=15930!
  INFO root [0x00002b08] [2020-10-28 20:11:34,627] - Components::addComponent[logger], uid=15930, componentID=210002, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002b08] [2020-10-28 20:11:34,632] - ---- baseapp Version: 1.2.7. ScriptVersion: 0.1.0. Protocol: 84173EFF21DE506F3117154D4C51407C. Config: Debug X86. Built: 19:02:14 Aug  4 2020. AppID: 720012. UID: 15930. PID: 7968 ----
  INFO root [0x00002b08] [2020-10-28 20:11:34,632] - Server : Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz with 2097151kB RAM
  INFO root [0x00002b08] [2020-10-28 20:11:34,632] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002b08] [2020-10-28 20:11:34,633] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,759] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,759] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,760] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,762] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,763] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,763] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,763] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,793] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002b08] [2020-10-28 20:11:34,823] - Script::install(): is successfully, Python=(3.4.2 (default, Aug  4 2020, 19:01:54) [MSC v.1925 32 bit (Intel)])!
  INFO root [0x00002b08] [2020-10-28 20:11:34,823] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,903] - loaded script:Avatar(1).
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,949] - loaded script:Halls(2).
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,956] - loaded script:Room(3).
 DEBUG root [0x00002b08] [2020-10-28 20:11:34,974] - loaded script:PrivateRoom(4).
  INFO root [0x00002b08] [2020-10-28 20:11:34,974] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002b08] [2020-10-28 20:11:34,974] - TelnetServer server is running on port 40000
  INFO root [0x00002b08] [2020-10-28 20:11:35,169] - ---- baseapp is running ----
 DEBUG root [0x00002b08] [2020-10-28 20:11:35,170] - Components::process(): Request for the process of identity...
  WARN root [0x00002b08] [2020-10-28 20:11:41,355] - Forwarding logs to logger[192.168.2.246:50313/0/0/0]...
 ERROR root [0x00002b08] [2020-10-28 21:38:07,485] - Components::removeComponentByChannel: logger : 210002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  INFO root [0x00002b08] [2020-10-28 21:38:07,501] - The following logs sent to logger failed:
  WARN root [0x00002b08] [2020-10-28 21:38:07,501] - ==> [2020-10-28 21:38:07 497] TCPPacketReceiver::processPendingEvents(192.168.2.246:50313): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002b08] [2020-10-28 21:38:07,501] - ==> [2020-10-28 21:38:07 505] Components::removeComponentByChannel: logger : 210002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  WARN root [0x00002b08] [2020-10-28 21:38:07,579] - TCPPacketReceiver::processPendingEvents(192.168.2.246:50314): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002b08] [2020-10-28 21:38:07,579] - Components::removeComponentByChannel: dbmgr : 42002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  INFO root [0x00002b08] [2020-10-28 21:38:07,595] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002b08] [2020-10-28 21:38:07,595] - onBaseAppShutDown: state=0
  INFO root [0x00002b08] [2020-10-28 21:38:07,595] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002b08] [2020-10-28 21:38:07,595] - onBaseAppShutDown: state=1
  INFO root [0x00002b08] [2020-10-28 21:38:07,595] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002b08] [2020-10-28 21:38:07,595] - onBaseAppShutDown: state=2
 ERROR root [0x00002b08] [2020-10-28 21:38:07,610] - Avatar::onCellWriteToDBCompleted(46): not found dbmgr!
 ERROR root [0x00002b08] [2020-10-28 21:38:07,626] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Avatar::~Avatar(): 46
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Room::~Room(): 47
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Halls::~Halls(): 1
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,626] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002b08] [2020-10-28 21:38:07,673] - Script::uninstall(): is successfully!
 DEBUG root [0x00002b08] [2020-10-28 21:38:07,673] - ThreadPool::destroy(): starting size 2.
