  INFO root [2020-10-11 18:20:14,259] - 
  INFO root [2020-10-11 18:20:14,260] - -----------------------------------------------------------------------------------------


  INFO root [2020-10-11 18:20:14,262] - Resmgr::initialize: KBE_ROOT=D:/kbengine_24pic/
  INFO root [2020-10-11 18:20:14,262] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine_24pic/kbe/res/;D:/kbengine_24pic/kbengine_stone_assets/;D:/kbengine_24pic/kbengine_stone_assets/scripts/;D:/kbengine_24pic/kbengine_stone_assets/res/
  INFO root [2020-10-11 18:20:14,262] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine_24pic/kbe/bin/server/
  INFO root [2020-10-11 18:20:14,267] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.2.246 ( 192.168.2.246:20013 )
  INFO root [2020-10-11 18:20:14,267] - NetworkInterface::initialize(EXTERNAL): address 192.168.2.246:20013, SOMAXCONN=128.
  INFO root [2020-10-11 18:20:14,270] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.2.246 ( 192.168.2.246:50729 )
  INFO root [2020-10-11 18:20:14,271] - NetworkInterface::initialize(INTERNAL): address 192.168.2.246:50729, SOMAXCONN=128.
  INFO root [2020-10-11 18:20:14,271] - server-configs:
  INFO root [2020-10-11 18:20:14,271] - 	internalAddr : 192.168.2.246:50729
  INFO root [2020-10-11 18:20:14,271] - 	externalAddr : 192.168.2.246:20013
  INFO root [2020-10-11 18:20:14,272] - 	componentID : 920002
  INFO root [2020-10-11 18:20:14,671] - Components::findLogger: found logger, addr:192.168.2.246:50723
  INFO root [2020-10-11 18:20:14,672] - Components::addComponent: reset orderLog, uid=14650!
  INFO root [2020-10-11 18:20:14,672] - Components::addComponent[logger], uid=14650, componentID=210002, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2020-10-11 18:20:14,675] - ---- loginapp Version: 1.2.7. ScriptVersion: 0.1.0. Protocol: A87D1428E6DE7B1742DD55BD6E5BAE8C. Config: Debug X86. Built: 19:01:57 Aug  4 2020. AppID: 920002. UID: 14650. PID: 14332 ----
  INFO root [2020-10-11 18:20:14,675] - Server : Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz with 2097151kB RAM
  INFO root [2020-10-11 18:20:14,676] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2020-10-11 18:20:14,676] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2020-10-11 18:20:14,802] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2020-10-11 18:20:14,802] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2020-10-11 18:20:14,803] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2020-10-11 18:20:14,806] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2020-10-11 18:20:14,806] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2020-10-11 18:20:14,806] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2020-10-11 18:20:14,807] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2020-10-11 18:20:14,838] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2020-10-11 18:20:14,865] - Script::install(): is successfully, Python=(3.4.2 (default, Aug  4 2020, 19:01:54) [MSC v.1925 32 bit (Intel)])!
  INFO root [2020-10-11 18:20:14,865] - Script::install(): KBExtra is successfully!
S_INFO root [2020-10-11 18:20:14,866] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2020-10-11 18:20:14,867] - TelnetServer server is running on port 31000
  INFO root [2020-10-11 18:20:15,070] - ---- loginapp is running ----
 DEBUG root [2020-10-11 18:20:15,071] - Components::process(): Request for the process of identity...
  WARN root [2020-10-11 18:20:21,253] - Forwarding logs to logger[192.168.2.246:50723/0/0/0]...
 ERROR root [2020-10-11 18:22:02,437] - Components::removeComponentByChannel: logger : 210002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  INFO root [2020-10-11 18:22:02,441] - The following logs sent to logger failed:
  WARN root [2020-10-11 18:22:02,441] - ==> [2020-10-11 18:22:02 437] TCPPacketReceiver::processPendingEvents(192.168.2.246:50723): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2020-10-11 18:22:02,442] - ==> [2020-10-11 18:22:02 438] Components::removeComponentByChannel: logger : 210002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  WARN root [2020-10-11 18:22:02,508] - TCPPacketReceiver::processPendingEvents(192.168.2.246:50724): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2020-10-11 18:22:02,510] - Components::removeComponentByChannel: dbmgr : 42002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  INFO root [2020-10-11 18:22:02,516] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2020-10-11 18:22:02,518] - onLoginAppShutDown()
  INFO root [2020-10-11 18:22:02,518] - Shutdowner::onShutdown: shutting down
  INFO root [2020-10-11 18:22:02,519] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2020-10-11 18:22:02,519] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2020-10-11 18:22:02,520] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2020-10-11 18:22:02,520] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2020-10-11 18:22:02,520] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2020-10-11 18:22:02,520] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2020-10-11 18:22:02,520] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2020-10-11 18:22:02,520] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2020-10-11 18:22:02,520] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2020-10-11 18:22:02,537] - Script::uninstall(): is successfully!
 DEBUG root [2020-10-11 18:22:02,538] - ThreadPool::destroy(): starting size 2.
  WARN root [2020-10-11 18:22:02,839] - ThreadPool::destroy(): waiting for thread(2)[0x1ab7028,0x1ab79e8,], try=1
  INFO root [2020-10-11 18:28:58,897] - 
  INFO root [2020-10-11 18:28:58,897] - -----------------------------------------------------------------------------------------


  INFO root [2020-10-11 18:28:58,898] - Resmgr::initialize: KBE_ROOT=D:/kbengine_24pic/
  INFO root [2020-10-11 18:28:58,899] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine_24pic/kbe/res/;D:/kbengine_24pic/kbengine_stone_assets/;D:/kbengine_24pic/kbengine_stone_assets/scripts/;D:/kbengine_24pic/kbengine_stone_assets/res/
  INFO root [2020-10-11 18:28:58,899] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine_24pic/kbe/bin/server/
  INFO root [2020-10-11 18:28:58,903] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.2.246 ( 192.168.2.246:20013 )
  INFO root [2020-10-11 18:28:58,904] - NetworkInterface::initialize(EXTERNAL): address 192.168.2.246:20013, SOMAXCONN=128.
  INFO root [2020-10-11 18:28:58,908] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.2.246 ( 192.168.2.246:50871 )
  INFO root [2020-10-11 18:28:58,908] - NetworkInterface::initialize(INTERNAL): address 192.168.2.246:50871, SOMAXCONN=128.
  INFO root [2020-10-11 18:28:58,908] - server-configs:
  INFO root [2020-10-11 18:28:58,909] - 	internalAddr : 192.168.2.246:50871
  INFO root [2020-10-11 18:28:58,909] - 	externalAddr : 192.168.2.246:20013
  INFO root [2020-10-11 18:28:58,909] - 	componentID : 920002
  INFO root [2020-10-11 18:28:59,167] - Components::findLogger: found logger, addr:192.168.2.246:50865
  INFO root [2020-10-11 18:28:59,167] - Components::addComponent: reset orderLog, uid=16361!
  INFO root [2020-10-11 18:28:59,167] - Components::addComponent[logger], uid=16361, componentID=210002, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2020-10-11 18:28:59,172] - ---- loginapp Version: 1.2.7. ScriptVersion: 0.1.0. Protocol: A87D1428E6DE7B1742DD55BD6E5BAE8C. Config: Debug X86. Built: 19:01:57 Aug  4 2020. AppID: 920002. UID: 16361. PID: 9152 ----
  INFO root [2020-10-11 18:28:59,173] - Server : Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz with 2097151kB RAM
  INFO root [2020-10-11 18:28:59,173] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2020-10-11 18:28:59,174] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2020-10-11 18:28:59,304] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2020-10-11 18:28:59,305] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2020-10-11 18:28:59,305] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2020-10-11 18:28:59,308] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2020-10-11 18:28:59,310] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2020-10-11 18:28:59,310] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2020-10-11 18:28:59,311] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2020-10-11 18:28:59,349] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2020-10-11 18:28:59,387] - Script::install(): is successfully, Python=(3.4.2 (default, Aug  4 2020, 19:01:54) [MSC v.1925 32 bit (Intel)])!
  INFO root [2020-10-11 18:28:59,388] - Script::install(): KBExtra is successfully!
S_INFO root [2020-10-11 18:28:59,390] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2020-10-11 18:28:59,391] - TelnetServer server is running on port 31000
  INFO root [2020-10-11 18:28:59,725] - ---- loginapp is running ----
 DEBUG root [2020-10-11 18:28:59,725] - Components::process(): Request for the process of identity...
  WARN root [2020-10-11 18:29:05,889] - Forwarding logs to logger[192.168.2.246:50865/0/0/0]...
 ERROR root [2020-10-11 18:55:55,738] - Components::removeComponentByChannel: logger : 210002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  INFO root [2020-10-11 18:55:55,741] - The following logs sent to logger failed:
  WARN root [2020-10-11 18:55:55,742] - ==> [2020-10-11 18:55:55 735] TCPPacketReceiver::processPendingEvents(192.168.2.246:50865): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2020-10-11 18:55:55,742] - ==> [2020-10-11 18:55:55 739] Components::removeComponentByChannel: logger : 210002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  WARN root [2020-10-11 18:55:55,831] - TCPPacketReceiver::processPendingEvents(192.168.2.246:50868): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2020-10-11 18:55:55,837] - Components::removeComponentByChannel: dbmgr : 42002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  INFO root [2020-10-11 18:55:55,841] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2020-10-11 18:55:55,843] - onLoginAppShutDown()
  INFO root [2020-10-11 18:55:55,843] - Shutdowner::onShutdown: shutting down
  INFO root [2020-10-11 18:55:55,843] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2020-10-11 18:55:55,844] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2020-10-11 18:55:55,844] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2020-10-11 18:55:55,845] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2020-10-11 18:55:55,845] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2020-10-11 18:55:55,845] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2020-10-11 18:55:55,845] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2020-10-11 18:55:55,845] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2020-10-11 18:55:55,846] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2020-10-11 18:55:55,870] - Script::uninstall(): is successfully!
 DEBUG root [2020-10-11 18:55:55,870] - ThreadPool::destroy(): starting size 2.
  WARN root [2020-10-11 18:55:56,172] - ThreadPool::destroy(): waiting for thread(2)[0x1b257b8,0x1b256e8,], try=1
  INFO root [2020-10-11 19:04:35,624] - 
  INFO root [2020-10-11 19:04:35,625] - -----------------------------------------------------------------------------------------


  INFO root [2020-10-11 19:04:35,625] - Resmgr::initialize: KBE_ROOT=D:/kbengine_24pic/
  INFO root [2020-10-11 19:04:35,626] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine_24pic/kbe/res/;D:/kbengine_24pic/kbengine_stone_assets/;D:/kbengine_24pic/kbengine_stone_assets/scripts/;D:/kbengine_24pic/kbengine_stone_assets/res/
  INFO root [2020-10-11 19:04:35,626] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine_24pic/kbe/bin/server/
  INFO root [2020-10-11 19:04:35,631] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.2.246 ( 192.168.2.246:20013 )
  INFO root [2020-10-11 19:04:35,631] - NetworkInterface::initialize(EXTERNAL): address 192.168.2.246:20013, SOMAXCONN=128.
  INFO root [2020-10-11 19:04:35,634] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.2.246 ( 192.168.2.246:49822 )
  INFO root [2020-10-11 19:04:35,635] - NetworkInterface::initialize(INTERNAL): address 192.168.2.246:49822, SOMAXCONN=128.
  INFO root [2020-10-11 19:04:35,635] - server-configs:
  INFO root [2020-10-11 19:04:35,635] - 	internalAddr : 192.168.2.246:49822
  INFO root [2020-10-11 19:04:35,635] - 	externalAddr : 192.168.2.246:20013
  INFO root [2020-10-11 19:04:35,635] - 	componentID : 920002
  INFO root [2020-10-11 19:04:35,792] - Components::findLogger: found logger, addr:192.168.2.246:49782
  INFO root [2020-10-11 19:04:35,792] - Components::addComponent: reset orderLog, uid=23140!
  INFO root [2020-10-11 19:04:35,792] - Components::addComponent[logger], uid=23140, componentID=210002, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2020-10-11 19:04:35,796] - ---- loginapp Version: 1.2.7. ScriptVersion: 0.1.0. Protocol: A87D1428E6DE7B1742DD55BD6E5BAE8C. Config: Debug X86. Built: 19:01:57 Aug  4 2020. AppID: 920002. UID: 23140. PID: 3084 ----
  INFO root [2020-10-11 19:04:35,796] - Server : Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz with 2097151kB RAM
  INFO root [2020-10-11 19:04:35,797] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2020-10-11 19:04:35,797] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2020-10-11 19:04:35,943] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2020-10-11 19:04:35,943] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2020-10-11 19:04:35,943] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2020-10-11 19:04:35,946] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2020-10-11 19:04:35,946] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2020-10-11 19:04:35,947] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2020-10-11 19:04:35,947] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2020-10-11 19:04:35,979] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2020-10-11 19:04:36,013] - Script::install(): is successfully, Python=(3.4.2 (default, Aug  4 2020, 19:01:54) [MSC v.1925 32 bit (Intel)])!
  INFO root [2020-10-11 19:04:36,014] - Script::install(): KBExtra is successfully!
S_INFO root [2020-10-11 19:04:36,045] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2020-10-11 19:04:36,045] - TelnetServer server is running on port 31000
  INFO root [2020-10-11 19:04:36,263] - ---- loginapp is running ----
 DEBUG root [2020-10-11 19:04:36,264] - Components::process(): Request for the process of identity...
  WARN root [2020-10-11 19:04:42,432] - Forwarding logs to logger[192.168.2.246:49782/0/0/0]...
 ERROR root [2020-10-11 19:06:32,950] - Components::removeComponentByChannel: logger : 210002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  INFO root [2020-10-11 19:06:32,950] - The following logs sent to logger failed:
  WARN root [2020-10-11 19:06:32,950] - ==> [2020-10-11 19:06:32 950] TCPPacketReceiver::processPendingEvents(192.168.2.246:49782): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2020-10-11 19:06:32,950] - ==> [2020-10-11 19:06:32 954] Components::removeComponentByChannel: logger : 210002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  WARN root [2020-10-11 19:06:33,044] - TCPPacketReceiver::processPendingEvents(192.168.2.246:49789): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2020-10-11 19:06:33,044] - Components::removeComponentByChannel: dbmgr : 42002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

  INFO root [2020-10-11 19:06:33,075] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2020-10-11 19:06:33,075] - onLoginAppShutDown()
  INFO root [2020-10-11 19:06:33,075] - Shutdowner::onShutdown: shutting down
  INFO root [2020-10-11 19:06:33,075] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2020-10-11 19:06:33,075] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2020-10-11 19:06:33,075] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2020-10-11 19:06:33,075] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2020-10-11 19:06:33,075] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2020-10-11 19:06:33,075] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2020-10-11 19:06:33,075] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2020-10-11 19:06:33,075] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2020-10-11 19:06:33,075] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2020-10-11 19:06:33,106] - Script::uninstall(): is successfully!
 DEBUG root [2020-10-11 19:06:33,106] - ThreadPool::destroy(): starting size 2.
